/**
 * TypeScript adapter for the Rust WASM CRDT module.
 *
 * The WASM module is generated by `wasm-pack build --target web` into ../pkg/.
 * Until the WASM build is set up, tests mock the module (see index.test.ts).
 */

export interface IDocumentCrdt {
  applyLocal(elementId: string, valueJson: string): string;
  mergeRemote(deltaJson: string): void;
  stateJson(): string;
  vectorClock(): string;
  elementCount(): number;
}

type WasmModule = { DocumentCrdt: new (peerId: string) => IDocumentCrdt };

let _wasm: WasmModule | null = null;

export async function initSync(): Promise<void> {
  if (_wasm) return;
  try {
    const mod = await import('../pkg/opencad_sync.js');
    await (mod as { default?: () => Promise<void> }).default?.();
    _wasm = mod as unknown as WasmModule;
  } catch {
    // WASM not yet compiled — createDocumentCrdt will throw with a helpful message
  }
}

export function createDocumentCrdt(peerId: string): IDocumentCrdt {
  if (!_wasm) {
    throw new Error(
      'WASM not initialized. Call initSync() first, or run: wasm-pack build --target web',
    );
  }
  return new _wasm.DocumentCrdt(peerId);
}
